name: Continuous Integration

on: [ pull_request ]

jobs:
  check-all-modules-are-tested:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check all modules are tested
      run: ./cd/check_modules.sh

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        modules:
        - name: Core
          values: :gaffer2,:core,:access,:cache,:common-util,:data,:exception,:graph,:operation,:serialisation,:store,:type
        - name: Accumulo
          values: :accumulo-store
        - name: Hbase
          values: :hbase-store
        - name: Parquet
          values: :parquet-store
        - name: Integration-Tests
          values: :integration-test-impl
        - name: Federated-And-Map
          values: :integration-test,:integration-test-framework,:federated-store,:map-store
        - name: REST
          values: :rest-api,:common-rest,:spring-rest,:spring-rest-library,:spring-rest-implementation,:store-implementation,:proxy-store
        - name: Examples
          values: :example,:basic,:basic-model,:basic-rest,:road-traffic,:road-traffic-model,:road-traffic-generators,:road-traffic-rest,:federated-demo
        - name: Big-Data-Libraries
          values: :flink-library,:hdfs-library,:spark,:spark-library,:spark-accumulo-library
        - name: Time-Library
          values: :library,:time-library
        - name: Caches
          values: :cache-library,:sketches-library,:bitmap-library,:hazelcast-cache-service,:jcs-cache-service

    env:
     MAVEN_OPTS: -Dmaven.wagon.http.retryHandler.count=10 -Dmaven.wagon.httpconnectionManager.ttlSeconds=60
    steps:

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2/repository
          !~/.m2/repository/uk
        key: gaffer-dependencies

    - name: clone pre-release-koryphe
      uses: actions/checkout@v2
      with:
        repository: gchq/koryphe
        ref: develop-v2

    - name: Install Koryphe
      run: mvn -q -B clean install -Pquick

    - uses: actions/checkout@v2

    - name: Install
      run: mvn -B -q clean install -P quick -pl ${{matrix.modules.values}} -am

    - name: Test
      run: mvn -B -q verify -P coverage -pl ${{matrix.modules.values}}

    - name: Upload Coverage
      uses: codecov/codecov-action@v1
